### ISSUE TITLE
Getting "Unknown error" for CeleryHealthCheck

### ISSUE THREAD

**Issue by GyanP** [codingjoe/django-health-check#144]
I digging this error and found the actual error "No result backend is configured" in
 https://github.com/KristianOellegaard/django-health-check/blob/master/health_check/contrib/celery/backends.py at line 20

result.get(timeout=timeout)

Can anyone help me on this?

Thanks

**Comment by codingjoe** [comment]
Hi @GyanP 

thanks for reaching out. I presume it's most likely because you don't have a result backend configured for celery. Check our there setup guide to see how its done.
If you have it setup, there is a trouble shooting guide for that:
http://docs.celeryproject.org/en/latest/getting-started/first-steps-with-celery.html#result-backend-doesn-t-work-or-tasks-are-always-in-pending-state

In any case, the message is valid and cause for action :)

Cheers
-Johannes

**Comment by DmytroLitvinov** [comment]
Hi @codingjoe , @KristianOellegaard ,

We are facing the same issue on `manage.py health_check` management command.
We use Redis as a broker and result backend.

Need to mention, that we have next version:
* celery[redis]==5.1.2

When we are running from shell same task which used in that command, we are getting result as expected. And also we checked that backend configured correctly:
```
from health_check.contrib.celery.tasks import add
add_result = add.apply_async(args=[4,4], expires=3)
print(add_result.backend)
```
And the response is: ` <celery.backends.redis.RedisBackend at 0x7f8a9ae043a0>`.

But when we are running management command, we see that result backend is `<celery.backends.base.DisabledBackend object at 0x7f8695ff0310>`
