### ISSUE TITLE
health_check.db in 3.3.0: FATAL:  connection limit exceeded for non-superusers

### ISSUE THREAD

**Issue by courcelm** [codingjoe/django-health-check#178]
The latest release (3.3.0) is having an issue for the health_check.db in 3.3.0. The database connections (Postgres in my case) are piling up every time the check is run. The issue is not found in 2.2.1 to 3.2.0.

I guess it is related to this new feature: "Use futures and parallel execution to improve performance"

**Comment by codingjoe** [comment]
@courcelm just in case. What database driver do you use? `psycopg2`?

**Comment by courcelm** [comment]
psycopg2==2.7.3.1
Django==1.11.7

**Comment by codingjoe** [comment]
@courcelm I am using the except same in some of my production applications. I can not reproduce this behavior. I am trying to find the difference here. Do you use connection pooling or something similar? What WSGI server do you use?

**Comment by courcelm** [comment]
@codingjoe   I'm not using any connection pooling. My WSGI server is gunicorn==19.7.1 with default worker_class (sync).

**Comment by codingjoe** [comment]
Hi @courcelm,

I investigated further and you seem to be right. Django does in deed use a connection per thread. That is usually not a problem, since the connections are ging closed at the end of each request.
That doesn't help much tho, if your Thread doesn't handle a request as in our case.

https://docs.djangoproject.com/en/2.0/ref/databases/#caveats

https://github.com/django/django/blob/cecc079168e8669138728d31611ff3a1e7eb3a9f/django/db/__init__.py#L57-L65

Anyhow, I think I know how to fix it. I will create a patch, it would be cool if you could try if the patch resolves your problem before I release it. Otherwise I don't really know hot to test that it fixes your problem.

**Comment by codingjoe** [comment]
https://github.com/KristianOellegaard/django-health-check/pull/182
