### ISSUE TITLE
CacheBackend 'unavailable: Cache key does not match' on first call

### ISSUE THREAD

**Issue by GabLeRoux** [codingjoe/django-health-check#203]
Hey there, thanks for this great package. I just gave this a try and it's really nice 👍.

I noticed that when django server just started, the first request to the health check url fails `CacheBackend` check with the following error:

```
 [2018-11-24 04:59:57] ERROR unavailable: Cache key does not match
 Traceback (most recent call last):
   File "/usr/local/lib/python3.4/site-packages/health_check/backends.py", line 30, in run_check
     self.check_status()
   File "/usr/local/lib/python3.4/site-packages/health_check/cache/backends.py", line 14, in check_status
     raise ServiceUnavailable("Cache key does not match")
 health_check.exceptions.ServiceUnavailable: unavailable: Cache key does not match
 [24/Nov/2018 04:59:57] "GET /health/ HTTP/1.1" 500 11588
```

According to the code, it's just making sure it can store something in the cache and then read it right after:

```python
            cache.set('djangohealtcheck_test', 'itworks', 1)
            if not cache.get("djangohealtcheck_test") == "itworks":
                raise ServiceUnavailable("Cache key does not match")
```

I did not configure `CACHES` in django settings yet, using python 3.4.2, django 1.9.5 (and wish to update soon). According to [following documentation](https://docs.djangoproject.com/en/1.9/topics/cache/#local-memory-caching), default caching backend is local memory caching.

This happened using `DEBUG=True`, I did not test elsewhere.

I'm writing this here, but the cache isn't critical on our side so I disabled it. Just wondering what's causing this.

**Comment by codingjoe** [comment]
Hi @GabLeRoux thanks for reaching out. I don't know if there really is much of a point in having a health check for the locmem cache backend, since it's simply a python object store running in the same process as your Django application. I think a health check only really makes sense if you rely on another service running as your cache backend. Therefore I would recommend to remove the check, if you don't use a proper cache, or better setup a cache.

Regarding the error, are sure that you are not using the dummy cache? This would one would not store anything and make the health check fail.

**Comment by GabLeRoux** [comment]
I noted this mostly for documentation. I’ll have a look, but I’m quite sure I was using the defaults. You’re right for a better setup, I’ll enable this when I’ll use memcached. Thanks :)

I’ll update here when I test against other backends. :+1:
