### ISSUE TITLE
allow set critical_service=False (BaseHealthCheckBackend) - Enhancement

### ISSUE THREAD

**Issue by SorianoMarmol** [codingjoe/django-health-check#241]
it would be interesting to be able to define critical_service = False (BaseHealthCheckBackend) based on a setting, for example

**Comment by codingjoe** [comment]
@SorianoMarmol thanks for reaching out.
I see the appeal in your request. It would be nice, it this was merely a configuration. Sadly it isn't that simple. You see, not all backends marked as critical by default. One setting that fits all, would probably also not help too many people, since most would want only one or two non-critical checks.
A setting for each check, seems like an overkill. It would add more complexity, than the advantages you gain. Especially since there is a simple solution, like inheritance and overwriting the attribute.
I hope that answer is acceptable to you, if maybe not fully satisfying. 
Best
-Joe
