### ISSUE TITLE
Non-default database connection are not being closed

### ISSUE THREAD

**Issue by ashexpertVersion2** [codingjoe/django-health-check#242]
I have defined 3 PostgreSQL database including 'default' but after each request a new idle connection appears on pg_stat_activity.
My router works this way: it routes all read query to 'read_replica' and all write query to 'write_replica' and no query routes to 'default'
I think the problematic part is here:

https://github.com/KristianOellegaard/django-health-check/blob/728b90251211ec34b0aa031e991955387d3fbcd9/health_check/mixins.py#L28-L37

It must call close on db that query was performing on not just default, am i missing something?

**Comment by codingjoe** [comment]
Hi @ashexpertVersion2,

thanks for reaching out. Yes, what you are describing is true. However, this only happens if you have [CONN_MAX_AGE](https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-CONN_MAX_AGE) set to something other than it's default value of `0`.

Anyhow, you are welcome to provide a patch that iterates of all connections and closes them.
However, I am curious why you would want your connections to live longer than a request.

Best
-Joe

**Comment by ashexpertVersion2** [comment]
i haven't set CONN_MAX_AGE to something other than default(which is 0). but anyway i am dealing with connection leak.
closest thing i have found is this:
[django-orm-connection-leak-with-threadpoolexcuter](https://stackoverflow.com/questions/57211476/django-orm-leaks-connections-when-using-threadpoolexecutor)

**Comment by codingjoe** [comment]
Ok, I see. Would you still care to submit a patch?

**Comment by ashexpertVersion2** [comment]
for sure.
