### ISSUE TITLE
Supports for Celery4

### ISSUE THREAD

**Issue by Beomi** [codingjoe/django-health-check#70]
Celery4 is relased now.
Does django-health-check supports celery 4?

**Comment by aleksihakli** [comment]
Hey @Beomi!

The current [Celery package we use for testing is actually 4.0.1](https://github.com/KristianOellegaard/django-health-check/blob/master/requirements-dev.txt), so the current version already supports Celery 4.

**Comment by aleksihakli** [comment]
*UPDATE*: On a closer inspection it seems like `@shared_task` in Celery 3 and 4 specific and the Celery support can be checked with the same code base for them:

http://docs.celeryproject.org/en/3.1/django/first-steps-with-django.html?highlight=shared_task
http://docs.celeryproject.org/en/v4.0.2/django/first-steps-with-django.html?highlight=shared_task

But Celery 2 actually uses the `@task` decorator that is available from `celery.task`:

http://docs.celeryproject.org/en/2.5-archived/reference/celery.app.task.html?highlight=app.task#module-celery.app.task

Since Celery 2 is actually the archived Celery version that does not receive any updates, perhaps we should do the following renames for the next release:

- Rename `health_check_celery` to `health_check_celery2` OR deprecate the old health checker AND
- Rename `health_check_celery3` to `health_check_celery` as it supports both Celery 3 and Celery 4. This way it is easier to understand that Celery 3 and 4 are actively supported and Celery 2 is the version that is specially treated.

**Comment by codingjoe** [comment]
As I said in the ticket. Just drop the celery 2 backend.

**Comment by aleksihakli** [comment]
@codingjoe This could be closed.
